#!/usr/bin/env python3
"""Rasterise a TrueType font into an 8x16 bitmap the kernel can link in.

The graphical console needs glyphs, and there is no font in memory once
the BIOS is gone.  This bakes codepoints 32..126 into one byte per
scanline, sixteen scanlines per glyph, and writes it out as NASM data.

Run it only when the font needs regenerating; the generated file is
checked in so the build does not depend on Python or on a font being
installed.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

FIRST = 32
LAST = 126
WIDTH = 8
HEIGHT = 16

DEFAULT_FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"


def render(font_path: str, size: int, dx: int, dy: int, threshold: int):
    from PIL import Image, ImageDraw, ImageFont

    font = ImageFont.truetype(font_path, size)
    glyphs = []

    for code in range(FIRST, LAST + 1):
        image = Image.new("L", (WIDTH, HEIGHT), 0)
        draw = ImageDraw.Draw(image)
        draw.text((dx, dy), chr(code), font=font, fill=255)

        rows = []
        for y in range(HEIGHT):
            bits = 0
            for x in range(WIDTH):
                if image.getpixel((x, y)) >= threshold:
                    # bit 7 is the leftmost pixel, so the kernel can just
                    # shift left and test the sign.
                    bits |= 0x80 >> x
            rows.append(bits)
        glyphs.append((code, rows))

    return glyphs


def preview(glyphs, text: str) -> str:
    table = {code: rows for code, rows in glyphs}
    lines = []
    for y in range(HEIGHT):
        line = []
        for character in text:
            rows = table.get(ord(character))
            if rows is None:
                line.append(" " * WIDTH)
                continue
            line.append(
                "".join("#" if rows[y] & (0x80 >> x) else "." for x in range(WIDTH))
            )
        lines.append(" ".join(line))
    return "\n".join(lines)


def emit(glyphs, font_path: str, size: int) -> str:
    out = [
        "; =====================================================================",
        ";  Jino-OS  ::  font.asm — the console typeface, 8x16 per glyph",
        "; ---------------------------------------------------------------------",
        ";  Generated by tools/mkfont.py; edit that rather than this file.",
        f";  Source: {pathlib.Path(font_path).name} at {size}px.",
        ";",
        ";  Codepoints 32..126, sixteen scanlines each, one byte per line with",
        ";  bit 7 as the leftmost pixel.  Anything outside that range is drawn",
        ";  as a blank by the caller.",
        "; =====================================================================",
        "",
        "                bits    32",
        "",
        "                global  font_glyphs",
        "                global  font_first",
        "                global  font_last",
        "                global  font_width",
        "                global  font_height",
        "",
        "                section .rodata",
        "                align   16",
        "font_glyphs:",
    ]

    # NASM treats a trailing backslash as a line continuation, so a
    # comment naming the backslash glyph would swallow the line after
    # it.  Spelling the punctuation out avoids that entirely.
    names = {
        32: "space",
        59: "semicolon",
        92: "backslash",
    }

    for code, rows in glyphs:
        label = names.get(code, chr(code))
        body = ", ".join(f"0x{value:02x}" for value in rows)
        out.append(f"                db      {body}   ; {code:3d} {label}")

    out += [
        "",
        "                align   4",
        f"font_first:     dd      {FIRST}",
        f"font_last:      dd      {LAST}",
        f"font_width:     dd      {WIDTH}",
        f"font_height:    dd      {HEIGHT}",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", default=DEFAULT_FONT)
    parser.add_argument("--size", type=int, default=14)
    parser.add_argument("--dx", type=int, default=0)
    parser.add_argument("--dy", type=int, default=0)
    parser.add_argument("--threshold", type=int, default=110)
    parser.add_argument("--output", default="kernel/font.asm")
    parser.add_argument("--preview", default="")
    args = parser.parse_args()

    try:
        glyphs = render(args.font, args.size, args.dx, args.dy, args.threshold)
    except ImportError:
        print("Pillow is needed to regenerate the font", file=sys.stderr)
        return 1

    if args.preview:
        print(preview(glyphs, args.preview))
        return 0

    pathlib.Path(args.output).write_text(emit(glyphs, args.font, args.size))
    print(f"wrote {args.output}: {len(glyphs)} glyphs, {WIDTH}x{HEIGHT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
